version: "3"
services:
  # service1: web
  web:
    # replace username/repo:tag with your name and image details
    image: zriemann1/hello:v0.0.1
    deploy:
      replicas: 8
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "60080:80"
    networks:
      - webnet
  # service2: virsualizer
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "64080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "63379:6379"
    volumes:
      - "~/redis/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:

