version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    port:
      - 67017:27017
    volumes:
      - "~/docker/mongodb/data/db:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    port:
      - 68081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example